services:
  - type: web
    name: authorizedzohopartners
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_NOTIFY_EMAIL
        value: manu@optimizemydata.com
      - key: BREVO_SENDER_EMAIL
        value: manu@optimizemydata.com
      - key: BREVO_SENDER_NAME
        value: Optimize My Data Website
